#!/bin/bash

EXTENSIONS="*.hpp *.cpp *.tpp"
DIRS="\
src \
src/gui3d \
src/cli \
src/psynth/base \
src/psynth/sound \
src/psynth/synth \
src/psynth/io \
src/psynth/node \
src/psynth/world \
src/psynth/psynth \
src/psynth/net \
src/test \
src/test/unit \
src/test/unit/psynth/sound \
src/test/unit/psynth/base \
"

PATTERNS=""
for ext in $EXTENSIONS; do
    for dir in $DIRS; do
	PATTERNS="$PATTERNS $dir/$ext"
    done
done

wc $PATTERNS
